/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import java.awt.Image;
import java.io.File;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;

/**
 *
 * @author monge
 */
public class MenuPrincipalCliente extends javax.swing.JDialog {

    /**
     * Creates new form MenuPrincipalCliente
     * 
     * 
     */
    public MenuPrincipalCliente() {
        initComponents();
        show(position);
    }
    int position = 0;
    
    public String[] takeimage(){
        File f = new File(getClass().getResource("/imagepath").getFile());
        String[] Images = f.list();
        return Images;
    }
    
    public void show(int index){
        String[] Images=takeimage();
        String img = Images[index];
        ImageIcon icon = new ImageIcon(getClass().getResource("/imagepath/"+img));
        Image image = icon.getImage().getScaledInstance(label_imagenes.getWidth(), label_imagenes.getHeight(), Image.SCALE_SMOOTH);
        label_imagenes.setIcon(new ImageIcon(image));
    }
    
    
    public MenuPrincipalCliente(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        encabezado_MenuCliente = new javax.swing.JLabel();
        label_bienvenido = new javax.swing.JLabel();
        label_nombreUsuario = new javax.swing.JLabel();
        boton_logout = new javax.swing.JButton();
        label_ConfiguracionCuentaCliente = new javax.swing.JLabel();
        boton_modificarCuentCliente = new javax.swing.JButton();
        label_pedidoNuevo = new javax.swing.JLabel();
        boton_realizarPedido = new javax.swing.JButton();
        label_hora = new javax.swing.JLabel();
        label_tiempo = new javax.swing.JLabel();
        label_fecha = new javax.swing.JLabel();
        label_imagenesMenuCliente = new javax.swing.JLabel();
        label_imagenes = new javax.swing.JLabel();
        label_back = new javax.swing.JLabel();
        label_next = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        encabezado_MenuCliente.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        encabezado_MenuCliente.setText("Menú Principal Cliente");

        label_bienvenido.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        label_bienvenido.setText("BIENVENIDO");

        label_nombreUsuario.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        label_nombreUsuario.setText("<<Nombre Usuario>>");

        boton_logout.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        boton_logout.setText("Logout");

        label_ConfiguracionCuentaCliente.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        label_ConfiguracionCuentaCliente.setText("Configuración de Cuenta");

        boton_modificarCuentCliente.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        boton_modificarCuentCliente.setText("Modificar Cuenta");

        label_pedidoNuevo.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        label_pedidoNuevo.setText("Pedido Nuevo");

        boton_realizarPedido.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        boton_realizarPedido.setText("REALIZAR PEDIDO");

        label_hora.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        label_hora.setText("Hora:");

        label_tiempo.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        label_tiempo.setText("hh:mm:ss");

        label_fecha.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        label_fecha.setText("dd/mm/aaaa");
        label_fecha.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        label_imagenesMenuCliente.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        label_imagenesMenuCliente.setText("Imágenes de los Productos en el Catálogo");

        label_back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/icons8_back_to_64px_2.png"))); // NOI18N
        label_back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                label_backMousePressed(evt);
            }
        });

        label_next.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/icons8_next_page_64px_1.png"))); // NOI18N
        label_next.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                label_nextMousePressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(label_bienvenido)
                .addGap(18, 18, 18)
                .addComponent(label_nombreUsuario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(boton_logout)
                .addGap(44, 44, 44))
            .addGroup(layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(label_ConfiguracionCuentaCliente, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(boton_realizarPedido)
                            .addComponent(label_fecha))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(boton_modificarCuentCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(label_pedidoNuevo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(61, 61, 61)
                                .addComponent(label_back, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(43, 43, 43)
                                .addComponent(label_imagenes, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(56, 56, 56)
                                .addComponent(label_next, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(25, 25, 25))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(label_imagenesMenuCliente)
                                .addGap(213, 213, 213))))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(encabezado_MenuCliente)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(label_hora)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(label_tiempo)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(encabezado_MenuCliente)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(label_bienvenido)
                            .addComponent(label_nombreUsuario)
                            .addComponent(boton_logout))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(113, 113, 113)
                                .addComponent(label_ConfiguracionCuentaCliente)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(label_next))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(boton_modificarCuentCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(115, 115, 115))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(128, 128, 128)
                                        .addComponent(label_back)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 107, Short.MAX_VALUE)))
                                .addComponent(label_pedidoNuevo)))
                        .addGap(18, 18, 18)
                        .addComponent(boton_realizarPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(56, 56, 56))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(95, 95, 95)
                        .addComponent(label_imagenes, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(label_imagenesMenuCliente)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_hora)
                    .addComponent(label_tiempo)
                    .addComponent(label_fecha))
                .addGap(51, 51, 51))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void label_nextMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_nextMousePressed
        new Thread();
        try {
            Thread.sleep(300);
        } catch (InterruptedException ex) {
            Logger.getLogger(MenuPrincipalCliente.class.getName()).log(Level.SEVERE, null, ex);
        }
        int p = this.label_imagenes.getX();
        
        if(p> -1){
            Animacion.Animacion.mover_izquierda(900,200,1,2,label_imagenes);
         
        }
        position = position+1;
        if(position>=takeimage().length){
            position = takeimage().length-1;
            
        }
        show(position);
    }//GEN-LAST:event_label_nextMousePressed

    private void label_backMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_backMousePressed
        new Thread();
        try {
            Thread.sleep(300);
        } catch (InterruptedException ex) {
            Logger.getLogger(MenuPrincipalCliente.class.getName()).log(Level.SEVERE, null, ex);
        }
        int p = this.label_imagenes.getX();
        
        if(p> -1){
            Animacion.Animacion.mover_izquierda(900,200,1,2,label_imagenes);
         
        }
        position = position-1;
        if(position<0){
            position = 0;
            
        }
        show(position);
    }//GEN-LAST:event_label_backMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipalCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipalCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipalCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipalCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                MenuPrincipalCliente dialog = new MenuPrincipalCliente(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton boton_logout;
    private javax.swing.JButton boton_modificarCuentCliente;
    private javax.swing.JButton boton_realizarPedido;
    private javax.swing.JLabel encabezado_MenuCliente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel label_ConfiguracionCuentaCliente;
    private javax.swing.JLabel label_back;
    private javax.swing.JLabel label_bienvenido;
    private javax.swing.JLabel label_fecha;
    private javax.swing.JLabel label_hora;
    private javax.swing.JLabel label_imagenes;
    private javax.swing.JLabel label_imagenesMenuCliente;
    private javax.swing.JLabel label_next;
    private javax.swing.JLabel label_nombreUsuario;
    private javax.swing.JLabel label_pedidoNuevo;
    private javax.swing.JLabel label_tiempo;
    // End of variables declaration//GEN-END:variables
}
