/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

/**
 *
 * @author monge
 */
public class MenúAdmin extends javax.swing.JDialog {

    /**
     * Creates new form MenúAdmin
     */
    public MenúAdmin(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        encabezado_menuAdmin = new javax.swing.JLabel();
        titulo_bienvenidoAdmin = new javax.swing.JLabel();
        label_opcionesCatalogo = new javax.swing.JLabel();
        boton_verCatalogo = new javax.swing.JButton();
        label_cuenta = new javax.swing.JLabel();
        boton_cambiarContraseña = new javax.swing.JButton();
        label_pedidos = new javax.swing.JLabel();
        boton_pedidosRealizados = new javax.swing.JButton();
        boton_logoutMenuAdmin = new javax.swing.JButton();
        boton_modificarCatalogo = new javax.swing.JButton();
        boton_estadisticasPedidos = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        encabezado_menuAdmin.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        encabezado_menuAdmin.setText("Menú Principal Administrador");

        titulo_bienvenidoAdmin.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        titulo_bienvenidoAdmin.setText("BIENVENIDO ADMINSTRADOR");

        label_opcionesCatalogo.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        label_opcionesCatalogo.setText("Opciones de Catálogo");

        boton_verCatalogo.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        boton_verCatalogo.setText("VER CATÁLOGO");
        boton_verCatalogo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_verCatalogoActionPerformed(evt);
            }
        });

        label_cuenta.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        label_cuenta.setText("Cuenta");

        boton_cambiarContraseña.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        boton_cambiarContraseña.setText("CAMBIAR CONTRASEÑA");
        boton_cambiarContraseña.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_cambiarContraseñaActionPerformed(evt);
            }
        });

        label_pedidos.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        label_pedidos.setText("Pedidos");

        boton_pedidosRealizados.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        boton_pedidosRealizados.setText("PEDIDOS REALIZADOS");
        boton_pedidosRealizados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_pedidosRealizadosActionPerformed(evt);
            }
        });

        boton_logoutMenuAdmin.setText("LOGOUT");

        boton_modificarCatalogo.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        boton_modificarCatalogo.setText("MODIFICAR CATÁLOGO");
        boton_modificarCatalogo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_modificarCatalogoActionPerformed(evt);
            }
        });

        boton_estadisticasPedidos.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        boton_estadisticasPedidos.setText("ESTADISTICAS DE PEDIDOS");
        boton_estadisticasPedidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_estadisticasPedidosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(encabezado_menuAdmin)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label_pedidos)
                            .addComponent(label_cuenta)
                            .addComponent(titulo_bienvenidoAdmin)
                            .addComponent(boton_cambiarContraseña))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(boton_verCatalogo)
                            .addComponent(label_opcionesCatalogo))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(boton_modificarCatalogo)
                        .addGap(129, 129, 129))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(boton_pedidosRealizados)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 328, Short.MAX_VALUE)
                        .addComponent(boton_estadisticasPedidos)
                        .addGap(97, 97, 97))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(boton_logoutMenuAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(encabezado_menuAdmin)
                .addGap(7, 7, 7)
                .addComponent(boton_logoutMenuAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addComponent(titulo_bienvenidoAdmin)
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(label_opcionesCatalogo)
                        .addGap(18, 18, 18)
                        .addComponent(boton_verCatalogo, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(boton_modificarCatalogo, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49)
                .addComponent(label_cuenta)
                .addGap(18, 18, 18)
                .addComponent(boton_cambiarContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(label_pedidos)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(boton_pedidosRealizados, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(boton_estadisticasPedidos, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 74, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void boton_verCatalogoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_verCatalogoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_boton_verCatalogoActionPerformed

    private void boton_cambiarContraseñaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_cambiarContraseñaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_boton_cambiarContraseñaActionPerformed

    private void boton_pedidosRealizadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_pedidosRealizadosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_boton_pedidosRealizadosActionPerformed

    private void boton_modificarCatalogoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_modificarCatalogoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_boton_modificarCatalogoActionPerformed

    private void boton_estadisticasPedidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_estadisticasPedidosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_boton_estadisticasPedidosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenúAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenúAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenúAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenúAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                MenúAdmin dialog = new MenúAdmin(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton boton_cambiarContraseña;
    private javax.swing.JButton boton_estadisticasPedidos;
    private javax.swing.JButton boton_logoutMenuAdmin;
    private javax.swing.JButton boton_modificarCatalogo;
    private javax.swing.JButton boton_pedidosRealizados;
    private javax.swing.JButton boton_verCatalogo;
    private javax.swing.JLabel encabezado_menuAdmin;
    private javax.swing.JLabel label_cuenta;
    private javax.swing.JLabel label_opcionesCatalogo;
    private javax.swing.JLabel label_pedidos;
    private javax.swing.JLabel titulo_bienvenidoAdmin;
    // End of variables declaration//GEN-END:variables
}
