/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Conexion.Conexion;
import General.AccionServidora;
import General.Peticion;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import org.apache.poi.ss.usermodel.Cell;
import org.apache.poi.ss.usermodel.Row;
import org.apache.poi.xssf.usermodel.XSSFSheet;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;

/**
 *
 * @author jcard
 */
public class LoginAdmin extends javax.swing.JDialog {

    /**
     * Creates new form LoginAdmin
     * @param parent
     * @param modal
     */
    public LoginAdmin(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        labelContraA = new javax.swing.JLabel();
        BRegresarLogCliente = new java.awt.Button();
        BIngresarMAdmin = new java.awt.Button();
        inputContraAdmin = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel2.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 204, 204));
        jLabel2.setText("Login de Administrador");

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel1.setText("Por favor inserte la contraseña del administrador");

        labelContraA.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        labelContraA.setText("Contraseña:");

        BRegresarLogCliente.setBackground(new java.awt.Color(204, 204, 204));
        BRegresarLogCliente.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        BRegresarLogCliente.setLabel("Regresar");
        BRegresarLogCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BRegresarLogClienteActionPerformed(evt);
            }
        });

        BIngresarMAdmin.setBackground(new java.awt.Color(204, 204, 204));
        BIngresarMAdmin.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        BIngresarMAdmin.setLabel("Ingresar");
        BIngresarMAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BIngresarMAdminActionPerformed(evt);
            }
        });

        inputContraAdmin.setBackground(new java.awt.Color(255, 255, 255));
        inputContraAdmin.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        inputContraAdmin.setForeground(new java.awt.Color(0, 0, 0));
        inputContraAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputContraAdminActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(labelContraA, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)
                        .addComponent(inputContraAdmin))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(83, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(70, 70, 70))
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addGap(70, 70, 70))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(BRegresarLogCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(202, Short.MAX_VALUE)
                    .addComponent(BIngresarMAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(165, 165, 165)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(64, 64, 64)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelContraA)
                    .addComponent(inputContraAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 166, Short.MAX_VALUE)
                .addComponent(BRegresarLogCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(280, Short.MAX_VALUE)
                    .addComponent(BIngresarMAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(105, 105, 105)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void inputContraAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputContraAdminActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputContraAdminActionPerformed

    private void BRegresarLogClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BRegresarLogClienteActionPerformed
        
        // Se le va a solicitar al servidor cerrar la ventana abierta
        Peticion peticionIngresar = new Peticion(AccionServidora.CERRAR_VENTANA, "" );
        
        Conexion conexion = new Conexion(peticionIngresar);

        boolean respuesta = (boolean) conexion.getRespuestaServer();
        
        if (respuesta){
            this.setVisible(false);
            this.dispose();
        }
    }//GEN-LAST:event_BRegresarLogClienteActionPerformed

    private void BIngresarMAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BIngresarMAdminActionPerformed
        
        // Se le va a solicitar al servidor verificar esta contraseña y se leera la contraseña actual
        // Si no esta vacia se revisa que este en el archivo
                    
        // Se abre el archivo llamado InformaciÃ³n y credenciales de los clientes
        FileInputStream archivo = null;
        try {
            archivo = new FileInputStream("ClientesSoda.xlsx");
        } catch (FileNotFoundException ex) {
            Logger.getLogger(LoginAdmin.class.getName()).log(Level.SEVERE, null, ex);
        }
        XSSFWorkbook libro = null;
        try {
            libro = new XSSFWorkbook(archivo);
        } catch (IOException ex) {
            Logger.getLogger(LoginAdmin.class.getName()).log(Level.SEVERE, null, ex);
        }

        // Se abre la hoja deseada del archivo
        XSSFSheet hoja = libro.getSheetAt(0);

        // Se obtiene la segunda fila del archivo
        Row fila = hoja.getRow(1);

        // Se obtienen los datos de la celda en esa fila y esa columna
        Cell celdaPassword = fila.getCell(5);

        // Se obtiene la contraseña de esa celda y se compara con la dada
        String contraseña = celdaPassword.getStringCellValue();
        
        String [] arrayTexto = new String[2];
        arrayTexto[0] = inputContraAdmin.getText();
        arrayTexto[1] = contraseña;
        
        Peticion peticionIngresar = new Peticion(AccionServidora.INGRESO_ADMIN, arrayTexto);
        Conexion conexion = new Conexion(peticionIngresar);
        String respuesta = (String) conexion.getRespuestaServer();
        
        if (respuesta.equals("ConVacia")){
            // Se creará una caja con un mensaje de error
            JOptionPane.showMessageDialog(null, "Por favor inserte una contraseña para continuar...", "Contraseña Vacía",JOptionPane.ERROR_MESSAGE);
        }
        else if(respuesta.equals("Incorrecta")){
            JOptionPane.showMessageDialog(null, "La contraseña es incorrecta","Error de Login",JOptionPane.ERROR_MESSAGE);
        }
        else{
            JFrame parentFrame =  (JFrame) this.getParent().getParent();
            MenuAdmin nueva = new MenuAdmin(parentFrame, true);
            nueva.setVisible(true);
        }
        
    }//GEN-LAST:event_BIngresarMAdminActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                LoginAdmin dialog = new LoginAdmin(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button BIngresarMAdmin;
    private java.awt.Button BRegresarLogCliente;
    private javax.swing.JPasswordField inputContraAdmin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel labelContraA;
    // End of variables declaration//GEN-END:variables
}
